services:
  app:
    container_name: app
    image: app
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - DATA_PROCESSOR=data_processor:3001
    depends_on:
      - data_processor

  data_processor:
    container_name: data_processor
    image: data_processor
    build: ./data_processor
    ports:
      - "3001:3001"
    volumes:
      - ./data_processor:/data_processor